"use client"
import localFont from "next/font/local";
import "./globals.css";
import '../assets/styles/index.scss';
import Header from "./InitialLayout/Header";
import Footer from "./InitialLayout/Footer";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <Header className='header'/>
        <main className='main'>
        {children}
        </main>
        <Footer className='footer'/>
        </AuthProvider>
      </body>
    </html>
  );
}
